const actions = {
  CREATE_FORM_MATERIALS: 'CREATE_FORM_MATERIALS',
  SUBMIT_ORDER: 'SUBMIT_ORDER',
  EDIT_ORDER_INFORMATION: 'EDIT_ORDER_INFORMATION',
  FINALIZE_ORDER:'FINALIZE_ORDER'

}

export default actions;
