const actions = {
  PRODUCT_FILTER: 'PRODUCT_FILTER',
  CREATE_REFINE_FILTER: 'CREATE_REFINE_FILTER',
  GET_PRODUCTS: 'GET_PRODUCTS',
  ERROR: 'ERROR',
  FIND_PRODUCT: 'FIND_PRODUCT',
  SET_PRODUCTS:'SET_PRODUCTS'
}

export default actions;
